# Generated by Django 4.1.1 on 2022-09-13 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
